### ISSUE TITLE
Chains should come back with ordering information

### ISSUE THREAD

**Issue by nsjames** [EOSPortal/eosportal-api#2]
For filtering and ordering purposes the `chains` should come back with a few properties:

- `chain_id`
- `total_voters` - Accumulation of voters ( not votes )
- `vote_percentage` - Percentage of total funds voted to date
- `boot_date` - The date the chain itself was booted
- `connected_bps` - The number of BPs registered ( and connected ) to this chain

**Comment by kesar** [comment]
done
